routes/web.php
<?php

use App\Http\Helpers\AppHelper;
use Illuminate\Support\Facades\Session;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

//Route::group(['middleware' => 'role:admin'], function() {
//    Route::get('/admin', function() {
//        return 'Welcome Admin';
//    });
//});

/**
 * Admin panel routes goes below
 */
Route::group(
	['namespace' => 'Backend', 'middleware' => ['guest']], function () {
		Route::get('/login', 'UserController@login')->name('login');
		Route::post('/login', 'UserController@authenticate');
		Route::get('/forgot', 'UserController@forgot')->name('forgot');
		Route::post('/forgot', 'UserController@forgot')
			->name('forgot');
		Route::get('/reset/{token}', 'UserController@reset')
			->name('reset');
		Route::post('/reset/{token}', 'UserController@reset')
			->name('reset');

	}
);

Route::group(
	['namespace' => 'Backend', 'middleware' => ['auth', 'permission']], function () {
		Route::get('/logout', 'UserController@logout')->name('logout');
		Route::get('/lock', 'UserController@lock')->name('lockscreen');
		Route::get('/dashboard', 'UserController@dashboard')->name('user.dashboard');

		//user management
		Route::resource('user', 'UserController');
		Route::get('/profile', 'UserController@profile')
			->name('profile');
		Route::post('/profile', 'UserController@profile')
			->name('profile');
		Route::get('/change-password', 'UserController@changePassword')
			->name('change_password');
		Route::post('/change-password', 'UserController@changePassword')
			->name('change_password');
		Route::post('user/status/{id}', 'UserController@changeStatus')
			->name('user.status');
		Route::any('user/{id}/permission', 'UserController@updatePermission')
			->name('user.permission');

		//user notification
		Route::get('/notification/unread', 'NotificationController@getUnReadNotification')
			->name('user.notification_unread');
		Route::get('/notification/read', 'NotificationController@getReadNotification')
			->name('user.notification_read');
		Route::get('/notification/all', 'NotificationController@getAllNotification')
			->name('user.notification_all');

		//system user management
		Route::get('/administrator/user', 'AdministratorController@userIndex')
			->name('administrator.user_index');
		Route::get('/administrator/user/create', 'AdministratorController@userCreate')
			->name('administrator.user_create');
		Route::post('/administrator/user/store', 'AdministratorController@userStore')
			->name('administrator.user_store');
		Route::get('/administrator/user/{id}/edit', 'AdministratorController@userEdit')
			->name('administrator.user_edit');
		Route::post('/administrator/user/{id}/update', 'AdministratorController@userUpdate')
			->name('administrator.user_update');
		Route::post('/administrator/user/{id}/delete', 'AdministratorController@userDestroy')
			->name('administrator.user_destroy');
		Route::post('administrator/user/status/{id}', 'AdministratorController@userChangeStatus')
			->name('administrator.user_status');

		Route::any('/administrator/user/reset-password', 'AdministratorController@userResetPassword')
			->name('administrator.user_password_reset');

		//user role manage
		Route::get('/role', 'UserController@roles')
			->name('user.role_index');
		Route::post('/role', 'UserController@roles')
			->name('user.role_destroy');
		Route::get('/role/create', 'UserController@roleCreate')
			->name('user.role_create');
		Route::post('/role/store', 'UserController@roleCreate')
			->name('user.role_store');
		Route::any('/role/update/{id}', 'UserController@roleUpdate')
			->name('user.role_update');

		// application settings routes
		Route::get('settings/institute', 'SettingsController@institute')
			->name('settings.institute');
		Route::post('settings/institute', 'SettingsController@institute')
			->name('settings.institute');

		// academic calendar
		Route::get('settings/academic-calendar', 'SettingsController@academicCalendarIndex')
			->name('settings.academic_calendar.index');
		Route::post('settings/academic-calendar', 'SettingsController@academicCalendarIndex')
			->name('settings.academic_calendar.destroy');
		Route::get('settings/academic-calendar/create', 'SettingsController@academicCalendarCru')
			->name('settings.academic_calendar.create');
		Route::post('settings/academic-calendar/create', 'SettingsController@academicCalendarCru')
			->name('settings.academic_calendar.store');
		Route::get('settings/academic-calendar/edit/{id}', 'SettingsController@academicCalendarCru')
			->name('settings.academic_calendar.edit');
		Route::post('settings/academic-calendar/update/{id}', 'SettingsController@academicCalendarCru')
			->name('settings.academic_calendar.update');

		//sms gateways
		Route::get('settings/sms-gateway', 'SettingsController@smsGatewayIndex')
			->name('settings.sms_gateway.index');
		Route::post('settings/sms-gateway', 'SettingsController@smsGatewayIndex')
			->name('settings.sms_gateway.destroy');
		Route::get('settings/sms-gateway/create', 'SettingsController@smsGatewayCru')
			->name('settings.sms_gateway.create');
		Route::post('settings/sms-gateway/create', 'SettingsController@smsGatewayCru')
			->name('settings.sms_gateway.store');
		Route::get('settings/sms-gateway/edit/{id}', 'SettingsController@smsGatewayCru')
			->name('settings.sms_gateway.edit');
		Route::post('settings/sms-gateway/update/{id}', 'SettingsController@smsGatewayCru')
			->name('settings.sms_gateway.update');

		//report settings
		Route::get('settings/report', 'SettingsController@report')
			->name('settings.report');
		Route::post('settings/report', 'SettingsController@report')
			->name('settings.report');

		// administrator routes
		//academic year
		Route::get('administrator/academic_year', 'AdministratorController@academicYearIndex')
			->name('administrator.academic_year');
		Route::post('administrator/academic_year', 'AdministratorController@academicYearIndex')
			->name('administrator.academic_year_destroy');
		Route::get('administrator/academic_year/create', 'AdministratorController@academicYearCru')
			->name('administrator.academic_year_create');
		Route::post('administrator/academic_year/create', 'AdministratorController@academicYearCru')
			->name('administrator.academic_year_store');
		Route::get('administrator/academic_year/edit/{id}', 'AdministratorController@academicYearCru')
			->name('administrator.academic_year_edit');
		Route::post('administrator/academic_year/update/{id}', 'AdministratorController@academicYearCru')
			->name('administrator.academic_year_update');
		Route::post('administrator/academic_year/status/{id}', 'AdministratorController@academicYearChangeStatus')
			->name('administrator.academic_year_status');

		// template
		//mail and sms
		Route::get('administrator/template/mailandsms', 'AdministratorController@templateMailAndSmsIndex')
			->name('administrator.template.mailsms.index');
		Route::post('administrator/template/mailandsms', 'AdministratorController@templateMailAndSmsIndex')
			->name('administrator.template.mailsms.destroy');
		Route::get('administrator/template/mailandsms/create', 'AdministratorController@templateMailAndSmsCru')
			->name('administrator.template.mailsms.create');
		Route::post('administrator/template/mailandsms/create', 'AdministratorController@templateMailAndSmsCru')
			->name('administrator.template.mailsms.store');
		Route::get('administrator/template/mailandsms/edit/{id}', 'AdministratorController@templateMailAndSmsCru')
			->name('administrator.template.mailsms.edit');
		Route::post('administrator/template/mailandsms/update/{id}', 'AdministratorController@templateMailAndSmsCru')
			->name('administrator.template.mailsms.update');
		// id card
		Route::get('administrator/template/idcard', 'AdministratorController@templateIdcardIndex')
			->name('administrator.template.idcard.index');
		Route::post('administrator/template/idcard', 'AdministratorController@templateIdcardIndex')
			->name('administrator.template.idcard.destroy');
		Route::get('administrator/template/idcard/create', 'AdministratorController@templateIdcardCru')
			->name('administrator.template.idcard.create');
		Route::post('administrator/template/idcard/create', 'AdministratorController@templateIdcardCru')
			->name('administrator.template.idcard.store');
		Route::get('administrator/template/idcard/edit/{id}', 'AdministratorController@templateIdcardCru')
			->name('administrator.template.idcard.edit');
		Route::post('administrator/template/idcard/update/{id}', 'AdministratorController@templateIdcardCru')
			->name('administrator.template.idcard.update');

		// academic routes
		// class
		Route::get('academic/class', 'AcademicController@classIndex')
			->name('academic.class');
		Route::post('academic/class', 'AcademicController@classIndex')
			->name('academic.class_destroy');
		Route::get('academic/class/create', 'AcademicController@classCru')
			->name('academic.class_create');
		Route::post('academic/class/create', 'AcademicController@classCru')
			->name('academic.class_store');
		Route::get('academic/class/edit/{id}', 'AcademicController@classCru')
			->name('academic.class_edit');
		Route::post('academic/class/update/{id}', 'AcademicController@classCru')
			->name('academic.class_update');
		Route::post('academic/class/status/{id}', 'AcademicController@classStatus')
			->name('academic.class_status');

		// section
		Route::get('academic/section', 'AcademicController@sectionIndex')
			->name('academic.section');
		Route::post('academic/section', 'AcademicController@sectionIndex')
			->name('academic.section_destroy');
		Route::get('academic/section/create', 'AcademicController@sectionCru')

app/Http/Controllers/Backend/AdmissionController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\IClass;
use App\Section;
use App\AcademicYear;
use App\Admission;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\View;
use Redirect;
use Validator;
use DB;
use App\Http\Helpers\AppHelper;
use Brian2694\Toastr\Facades\Toastr;

class AdmissionController extends Controller
{
    public function index()
    {
    	  $classes = IClass::all();
          $class_id =null;
          $sections = Section::where('status', AppHelper::ACTIVE)
                ->where('class_id', $class_id)
                ->get();
    	  $academic_years = AcademicYear::where('status', '1')->orderBy('id', 'desc')->get();

    	  $admission =array();
    	  return View::Make('backend.admission.admissionlist', compact('classes','sections','academic_years','admission'));
    }

    public function list()
    {

      $rules=[
            'class_id' => 'required',
            'academic_year_id' => 'required',


        ];
        $validator = \Validator::make(Input::all(), $rules);
        if ($validator->fails())
        {

            return Redirect::to('/admission')->withErrors($validator);
        }

          $classes = IClass::all();
          $class_id =null;
          $sections = Section::where('status', AppHelper::ACTIVE)
                ->where('class_id', $class_id)
                ->get();
    	  $academic_years = AcademicYear::where('status', '1')->orderBy('id', 'desc')->get();

    	$admission =Admission::with(['academicyear','class','section'])
    	                      ->where('academic_year_id',Input::get('academic_year_id'))
    	                      ->where('class_id',Input::get('class_id'))
    	                      ->where('section_id',Input::get('section'))
    	                      ->get();
    	 return View::Make('backend.admission.admissionlist', compact('classes','sections','academic_years','admission'));                     
    	                   
    }

    public function active($id)
    {
    	$admission=Admission::find($id);
    	$admission->status=false;
    	$admission->save();
    	Toastr::success('Admission Status Update:','Success');
    	return redirect()->back();
    }

    public function inactive($id)
    {
    	$admission=Admission::find($id);
    	$admission->status=true;
    	$admission->save();
    	Toastr::success('Admission Status Update:','Success');
    	return redirect()->back();
    }

    public function create()
    {
    	  $classes = IClass::all();
          $class_id =null;
          $sections = Section::where('status', AppHelper::ACTIVE)
                ->where('class_id', $class_id)
                ->get();
    	  $academic_years = AcademicYear::where('status', '1')->orderBy('id', 'desc')->get();

    	   return View::Make('backend.admission.admissioncreate', compact('classes','sections','academic_years'));   

    }

    public function postadmission()
    {
    	 $rules=[
            'class_id' => 'required',
            'academic_year_id' => 'required',
            'name' => 'required',
            'open' => 'required',
            'close' => 'required',


        ];
        $validator = \Validator::make(Input::all(), $rules);
        if ($validator->fails())
        {

            return Redirect::to('/admission/create')->withErrors($validator);
        }

        else
        {
        	$admission =new Admission();
        	$admission->academic_year_id=Input::get('academic_year_id');
        	$admission->class_id=Input::get('class_id');
        	$admission->section_id=Input::get('section');
        	$admission->name=Input::get('name');
        	$admission->open=Input::get('open');
        	$admission->close=Input::get('close');
        	$admission->save();
        	Toastr::success('Admission Craete Successfully:','Success');
        	return Redirect::to('exam/admission');

        }
    }
}

app/Http/Controllers/Backend/ClassOffController.php
<?php

namespace App\Http\Controllers\Backend;

use App\ClassOff;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\View;

class ClassOffController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		$offdays = ClassOff::where('status', 1)->get();
		return View::Make('backend.student.class-off.list', compact('offdays'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		$rules = [
			'offDate' => 'required',
			'oType' => 'required',

		];
		$validator = \Validator::make(Input::all(), $rules);
		if ($validator->fails()) {
			return Redirect::to('/class-off')->withErrors($validator);
		} else {

			$offDateStart = \Carbon\Carbon::createFromFormat('d/m/Y', Input::get('offDate'));
			$offDateEnd = null;
			if (strlen(Input::get('offDateEnd'))) {
				$offDateEnd = \Carbon\Carbon::createFromFormat('d/m/Y', Input::get('offDateEnd'));
			}

			$offList = [];
			$desc = Input::get('description');
			$oType = Input::get('oType');

			if ($offDateEnd) {
				if ($offDateEnd < $offDateStart) {
					$messages = $validator->errors();
					$messages->add('Wrong Input!', 'Date End can\'t be less than start date!');
					return Redirect::to('/class-off')->withErrors($messages)->withInput();
				}

				$start_time = strtotime($offDateStart);
				$end_time = strtotime($offDateEnd);
				for ($i = $start_time; $i <= $end_time; $i += 86400) {
					$offList[] = [
						'offDate' => date('Y-m-d', $i),
						'created_at' => \Carbon\Carbon::now(),
						'updated_at' => \Carbon\Carbon::now(),
						'description' => $desc,
						'oType' => $oType,
						'status' => 1,
					];

				}

			} else {
				$offList[] = [
					'offDate' => $offDateStart->format('Y-m-d'),
					'created_at' => \Carbon\Carbon::now(),
					'updated_at' => \Carbon\Carbon::now(),
					'description' => $desc,
					'oType' => $oType,
					'status' => 1,
				];
			}

			ClassOff::insert($offList);

			return Redirect::to('/class-off')->with("success", "Class off entry added.");
		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		$classOff = ClassOff::where('status', 1)->where('id', $id)->first();

		if (!$classOff) {
			return Redirect::to('/class-off')->with("error", "Class off entry not found!");

		}
		$classOff->status = 0;
		$classOff->save();

		return Redirect::to('/class-off')->with("success", "Class off entry deleted successfully.");
	}
}

resources/views/backend/user/add.blade.php
<!-- Master page  -->
@extends('backend.layouts.master')

<!-- Page title -->
@section('pageTitle') User @endsection
<!-- End block -->

<!-- Page body extra class -->
@section('bodyCssClass') @endsection
<!-- End block -->

<!-- BEGIN PAGE CONTENT-->
@section('pageContent')
    <!-- Section header -->
    <section class="content-header">
        <h1>
            User
            <small>@if($user) Update @else Add New @endif</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{URL::route('user.dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{{URL::route('user.index')}}"><i class="fa icon-user"></i> User</a></li>
            <li class="active">@if($user) Update @else Add @endif</li>
        </ol>
    </section>
    <!-- ./Section header -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <form novalidate id="entryForm" action="@if($user) {{URL::Route('user.update', $user->id)}} @else {{URL::Route('user.store')}} @endif" method="post" enctype="multipart/form-data">
                        <div class="box-header">
                            <div class="callout callout-danger">
                                <p><b>Note:</b> Create a role before create user if not exist.</p>
                            </div>
                        </div>
                        <div class="box-body">
                            @csrf
                            @if($user)  {{ method_field('PATCH') }} @endif
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group has-feedback">
                                        <label for="name">Name<span class="text-danger">*</span></label>
                                        <input autofocus type="text" class="form-control" name="name" placeholder="name" value="@if($user){{ $user->name }}@else{{old('name')}}@endif" required minlength="2" maxlength="255">
                                        <span class="fa fa-info form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('name') }}</span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group has-feedback">
                                        <label for="email">Email<span class="text-danger">*</span></label>
                                        <input  type="email" class="form-control" name="email"  placeholder="email address" value="@if($user){{$user->email}}@else{{old('email')}}@endif" maxlength="100" required>
                                        <span class="fa fa-envelope form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('email') }}</span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group has-feedback">
                                        <label for="role_id">User Role
                                            <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Set a user role"></i>
                                        </label>
                                        {!! Form::select('role_id', $roles, $role , ['placeholder' => 'Pick a role...','class' => 'form-control select2', 'required' => 'true']) !!}
                                        <span class="form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('role_id') }}</span>
                                    </div>
                                </div>
                            </div>
                            @if(!$user)
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group has-feedback">
                                        <label for="username">Username<span class="text-danger">*</span></label>
                                        <input  type="text" class="form-control" value="" name="username" required minlength="5" maxlength="255">
                                        <span class="glyphicon glyphicon-info-sign form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('username') }}</span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group has-feedback">
                                        <label for="password">Password<span class="text-danger">*</span></label>
                                        <input type="password" class="form-control" name="password" placeholder="Password" required minlength="6" maxlength="50">
                                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('password') }}</span>
                                    </div>
                                </div>
                            </div>
                                @endif

                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{URL::route('user.index')}}" class="btn btn-default">Cancel</a>
                            <button type="submit" class="btn btn-info pull-right"><i class="fa @if($user) fa-refresh @else fa-plus-circle @endif"></i> @if($user) Update @else Add @endif</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
@endsection
<!-- END PAGE CONTENT-->

<!-- BEGIN PAGE JS-->
@section('extraScript')
    <script type="text/javascript">
        $(document).ready(function () {
            Generic.initCommonPageJS();
        });
    </script>
@endsection
<!-- END PAGE JS-->

resources/views/backend/user/list.blade.php
<!-- Master page  -->
@extends('backend.layouts.master')

<!-- Page title -->
@section('pageTitle') User @endsection
<!-- End block -->

<!-- Page body extra class -->
@section('bodyCssClass') @endsection
<!-- End block -->

<!-- BEGIN PAGE CONTENT-->
@section('pageContent')
    <!-- Section header -->
    <section class="content-header">
        <h1>
            User
            <small>List</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{URL::route('user.dashboard')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active">User</li>
        </ol>
    </section>
    <!-- ./Section header -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header">
                        <div class="box-tools pull-right">
                            <a class="btn btn-info btn-sm" href="{{ URL::route('user.create') }}"><i class="fa fa-plus-circle"></i> Add New</a>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body margin-top-20">
                        <div class="table-responsive">
                        <table id="listDataTable" class="table table-bordered table-striped list_view_table display responsive no-wrap" width="100%">
                            <thead>
                            <tr>
                                <th width="5%">#</th>
                                <th width="20%">Name</th>
                                <th width="10%">Username</th>
                                <th width="30%">Email</th>
                                <th width="10%">Role</th>
                                <th width="10%">Status</th>
                                <th class="notexport" width="15%">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>
                                        {{$loop->iteration}}
                                    </td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->username }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->role }}</td>
                                    <td>
                                        <!-- todo: have problem in mobile device -->
                                        <input class="statusChange" type="checkbox" data-pk="{{$user->id}}" @if($user->status) checked @endif data-toggle="toggle" data-on="<i class='fa fa-check-circle'></i>" data-off="<i class='fa fa-ban'></i>" data-onstyle="success" data-offstyle="danger">
                                    </td>
                                    <td>
                                        {{--<div class="btn-group">--}}
                                            {{--<a title="Details"  href="{{URL::route('user.show',$user->id)}}"  class="btn btn-primary btn-sm"><i class="fa fa-eye"></i>--}}
                                            {{--</a>--}}
                                        {{--</div>--}}
                                        <div class="btn-group">
                                            <a title="Edit" href="{{URL::route('user.edit',$user->id)}}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i></a>
                                            </a>
                                        </div>
                                        <!-- todo: have problem in mobile device -->
                                        <div class="btn-group">
                                            <a title="Edit Permission" href="{{URL::route('user.permission',$user->id)}}" class="btn btn-info btn-sm"><i class="fa fa-user-times"></i></a>
                                            </a>
                                        </div>
                                        <div class="btn-group">
                                            <form  class="myAction" method="POST" action="{{URL::route('user.destroy', $user->id)}}">
                                                @csrf
                                                <input name="_method" type="hidden" value="DELETE">
                                                <button type="submit" class="btn btn-danger btn-sm" title="Delete">
                                                    <i class="fa fa-fw fa-trash"></i>
                                                </button>
                                            </form>
                                        </div>

                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                            <tfoot>
                            <tr>
                                <th width="5%">#</th>
                                <th width="20%">Name</th>
                                <th width="10%">Username</th>
                                <th width="30%">Email</th>
                                <th width="10%">Role</th>
                                <th width="10%">Status</th>
                                <th class="notexport" width="15%">Action</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->
@endsection
<!-- END PAGE CONTENT-->

<!-- BEGIN PAGE JS-->
@section('extraScript')
    <script type="text/javascript">
        $(document).ready(function () {
            window.postUrl = '{{URL::Route("user.status", 0)}}';
            window.changeExportColumnIndex = 5;
            Generic.initCommonPageJS();
            Generic.initDeleteDialog();
        });
    </script>
@endsection
<!-- END PAGE JS-->